# Generated by Django 5.0.6 on 2024-05-13 23:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("every_week_reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EveryWeekReports",
            new_name="EveryWeekReportsData",
        ),
    ]
