# Generated by Django 5.0.6 on 2024-05-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databasedata",
            name="file",
            field=models.FileField(upload_to="database/"),
        ),
    ]
